name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: snk3981/bong-go
          stage: main
          yaml: >
            name: bongo-server

            app: node@16

            options:
              env:
                - name: NODE_ENV
                  value: production
                - name: JWT_SECRET
                  value: ${{ secrets.JWT_SECRET }}
                - name: DATABASE_URL
                  value: ${{ secrets.DATABASE_URL }}
              ports: "3001"
              build: npm run build
              start: npm run start:prod
              buildenv: []
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: nest.js